// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static FirebaseOptions web = FirebaseOptions(
    apiKey:dotenv.env['FAREBASE_API_KEY']!,
    appId: '1:78902634062:web:f2c15a105498593dabc51f',
    messagingSenderId: '78902634062',
    projectId: 'app-pesan-makanan',
    authDomain: 'app-pesan-makanan.firebaseapp.com',
    storageBucket: 'app-pesan-makanan.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FAREBASE_API_KEY']!,
    appId: '1:78902634062:android:2425392ecd7be6a1abc51f',
    messagingSenderId: '78902634062',
    projectId: 'app-pesan-makanan',
    storageBucket: 'app-pesan-makanan.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FAREBASE_API_KEY']!,
    appId: '1:78902634062:ios:30d72a32bea11889abc51f',
    messagingSenderId: '78902634062',
    projectId: 'app-pesan-makanan',
    storageBucket: 'app-pesan-makanan.appspot.com',
    iosClientId: '78902634062-jrve7m14jnolblm2mld510v9hnl08i17.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationPesanMakanan',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FAREBASE_API_KEY']!,
    appId: '1:78902634062:ios:6b4fad517976fac9abc51f',
    messagingSenderId: '78902634062',
    projectId: 'app-pesan-makanan',
    storageBucket: 'app-pesan-makanan.appspot.com',
    iosClientId: '78902634062-mpojs33ibi8t1l9itg8sncc7g9ve8t0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationPesanMakanan.RunnerTests',
  );
}
